#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HutechWork.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DB_Vieclam")]
	public partial class dbQlHutechWorkDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHITIETTUYENDUNG(CHITIETTUYENDUNG instance);
    partial void UpdateCHITIETTUYENDUNG(CHITIETTUYENDUNG instance);
    partial void DeleteCHITIETTUYENDUNG(CHITIETTUYENDUNG instance);
    partial void InsertTHONGTINCANHAN(THONGTINCANHAN instance);
    partial void UpdateTHONGTINCANHAN(THONGTINCANHAN instance);
    partial void DeleteTHONGTINCANHAN(THONGTINCANHAN instance);
    partial void InsertHOSOXINVIEC(HOSOXINVIEC instance);
    partial void UpdateHOSOXINVIEC(HOSOXINVIEC instance);
    partial void DeleteHOSOXINVIEC(HOSOXINVIEC instance);
    partial void InsertLUOTUNGTUYEN(LUOTUNGTUYEN instance);
    partial void UpdateLUOTUNGTUYEN(LUOTUNGTUYEN instance);
    partial void DeleteLUOTUNGTUYEN(LUOTUNGTUYEN instance);
    partial void InsertNOPDON(NOPDON instance);
    partial void UpdateNOPDON(NOPDON instance);
    partial void DeleteNOPDON(NOPDON instance);
    partial void InsertNGANH(NGANH instance);
    partial void UpdateNGANH(NGANH instance);
    partial void DeleteNGANH(NGANH instance);
    partial void InsertNGOAINGU(NGOAINGU instance);
    partial void UpdateNGOAINGU(NGOAINGU instance);
    partial void DeleteNGOAINGU(NGOAINGU instance);
    partial void InsertPHIEUDANGTUYEN(PHIEUDANGTUYEN instance);
    partial void UpdatePHIEUDANGTUYEN(PHIEUDANGTUYEN instance);
    partial void DeletePHIEUDANGTUYEN(PHIEUDANGTUYEN instance);
    partial void InsertTAIKHOAN_CN(TAIKHOAN_CN instance);
    partial void UpdateTAIKHOAN_CN(TAIKHOAN_CN instance);
    partial void DeleteTAIKHOAN_CN(TAIKHOAN_CN instance);
    partial void InsertTAIKHOAN_DN(TAIKHOAN_DN instance);
    partial void UpdateTAIKHOAN_DN(TAIKHOAN_DN instance);
    partial void DeleteTAIKHOAN_DN(TAIKHOAN_DN instance);
    partial void InsertTTDOANHNGHIEP(TTDOANHNGHIEP instance);
    partial void UpdateTTDOANHNGHIEP(TTDOANHNGHIEP instance);
    partial void DeleteTTDOANHNGHIEP(TTDOANHNGHIEP instance);
    partial void InsertTHANHPHO(THANHPHO instance);
    partial void UpdateTHANHPHO(THANHPHO instance);
    partial void DeleteTHANHPHO(THANHPHO instance);
    #endregion
		
		public dbQlHutechWorkDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DB_VieclamConnectionString2"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQlHutechWorkDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQlHutechWorkDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQlHutechWorkDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQlHutechWorkDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHITIETTUYENDUNG> CHITIETTUYENDUNGs
		{
			get
			{
				return this.GetTable<CHITIETTUYENDUNG>();
			}
		}
		
		public System.Data.Linq.Table<THONGTINCANHAN> THONGTINCANHANs
		{
			get
			{
				return this.GetTable<THONGTINCANHAN>();
			}
		}
		
		public System.Data.Linq.Table<HOSOXINVIEC> HOSOXINVIECs
		{
			get
			{
				return this.GetTable<HOSOXINVIEC>();
			}
		}
		
		public System.Data.Linq.Table<LUOTUNGTUYEN> LUOTUNGTUYENs
		{
			get
			{
				return this.GetTable<LUOTUNGTUYEN>();
			}
		}
		
		public System.Data.Linq.Table<NOPDON> NOPDONs
		{
			get
			{
				return this.GetTable<NOPDON>();
			}
		}
		
		public System.Data.Linq.Table<NGANH> NGANHs
		{
			get
			{
				return this.GetTable<NGANH>();
			}
		}
		
		public System.Data.Linq.Table<NGOAINGU> NGOAINGUs
		{
			get
			{
				return this.GetTable<NGOAINGU>();
			}
		}
		
		public System.Data.Linq.Table<PHIEUDANGTUYEN> PHIEUDANGTUYENs
		{
			get
			{
				return this.GetTable<PHIEUDANGTUYEN>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN_CN> TAIKHOAN_CNs
		{
			get
			{
				return this.GetTable<TAIKHOAN_CN>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN_DN> TAIKHOAN_DNs
		{
			get
			{
				return this.GetTable<TAIKHOAN_DN>();
			}
		}
		
		public System.Data.Linq.Table<TTDOANHNGHIEP> TTDOANHNGHIEPs
		{
			get
			{
				return this.GetTable<TTDOANHNGHIEP>();
			}
		}
		
		public System.Data.Linq.Table<THANHPHO> THANHPHOs
		{
			get
			{
				return this.GetTable<THANHPHO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETTUYENDUNG")]
	public partial class CHITIETTUYENDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPDT;
		
		private string _TIEUDE;
		
		private string _CHUCDANH;
		
		private string _CAPBAC;
		
		private int _MANGANH;
		
		private string _DIACHILAMVIEC;
		
		private System.Nullable<int> _MATHANHPHO;
		
		private System.Nullable<double> _MUCLUONGTOITHIEU;
		
		private System.Nullable<double> _MUCLUONGTOIDA;
		
		private string _MOTACV;
		
		private string _YEUCAUCV;
		
		private string _KYNANG;
		
		private string _NGUOILIENHE;
		
		private string _EMAILLIENHE;
		
		private EntityRef<NGANH> _NGANH;
		
		private EntityRef<PHIEUDANGTUYEN> _PHIEUDANGTUYEN;
		
		private EntityRef<THANHPHO> _THANHPHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPDTChanging(int value);
    partial void OnMAPDTChanged();
    partial void OnTIEUDEChanging(string value);
    partial void OnTIEUDEChanged();
    partial void OnCHUCDANHChanging(string value);
    partial void OnCHUCDANHChanged();
    partial void OnCAPBACChanging(string value);
    partial void OnCAPBACChanged();
    partial void OnMANGANHChanging(int value);
    partial void OnMANGANHChanged();
    partial void OnDIACHILAMVIECChanging(string value);
    partial void OnDIACHILAMVIECChanged();
    partial void OnMATHANHPHOChanging(System.Nullable<int> value);
    partial void OnMATHANHPHOChanged();
    partial void OnMUCLUONGTOITHIEUChanging(System.Nullable<double> value);
    partial void OnMUCLUONGTOITHIEUChanged();
    partial void OnMUCLUONGTOIDAChanging(System.Nullable<double> value);
    partial void OnMUCLUONGTOIDAChanged();
    partial void OnMOTACVChanging(string value);
    partial void OnMOTACVChanged();
    partial void OnYEUCAUCVChanging(string value);
    partial void OnYEUCAUCVChanged();
    partial void OnKYNANGChanging(string value);
    partial void OnKYNANGChanged();
    partial void OnNGUOILIENHEChanging(string value);
    partial void OnNGUOILIENHEChanged();
    partial void OnEMAILLIENHEChanging(string value);
    partial void OnEMAILLIENHEChanged();
    #endregion
		
		public CHITIETTUYENDUNG()
		{
			this._NGANH = default(EntityRef<NGANH>);
			this._PHIEUDANGTUYEN = default(EntityRef<PHIEUDANGTUYEN>);
			this._THANHPHO = default(EntityRef<THANHPHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPDT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAPDT
		{
			get
			{
				return this._MAPDT;
			}
			set
			{
				if ((this._MAPDT != value))
				{
					if (this._PHIEUDANGTUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPDTChanging(value);
					this.SendPropertyChanging();
					this._MAPDT = value;
					this.SendPropertyChanged("MAPDT");
					this.OnMAPDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TIEUDE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TIEUDE
		{
			get
			{
				return this._TIEUDE;
			}
			set
			{
				if ((this._TIEUDE != value))
				{
					this.OnTIEUDEChanging(value);
					this.SendPropertyChanging();
					this._TIEUDE = value;
					this.SendPropertyChanged("TIEUDE");
					this.OnTIEUDEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCDANH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CHUCDANH
		{
			get
			{
				return this._CHUCDANH;
			}
			set
			{
				if ((this._CHUCDANH != value))
				{
					this.OnCHUCDANHChanging(value);
					this.SendPropertyChanging();
					this._CHUCDANH = value;
					this.SendPropertyChanged("CHUCDANH");
					this.OnCHUCDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPBAC", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string CAPBAC
		{
			get
			{
				return this._CAPBAC;
			}
			set
			{
				if ((this._CAPBAC != value))
				{
					this.OnCAPBACChanging(value);
					this.SendPropertyChanging();
					this._CAPBAC = value;
					this.SendPropertyChanged("CAPBAC");
					this.OnCAPBACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGANH", DbType="Int NOT NULL")]
		public int MANGANH
		{
			get
			{
				return this._MANGANH;
			}
			set
			{
				if ((this._MANGANH != value))
				{
					if (this._NGANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANGANHChanging(value);
					this.SendPropertyChanging();
					this._MANGANH = value;
					this.SendPropertyChanged("MANGANH");
					this.OnMANGANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHILAMVIEC", DbType="NVarChar(100)")]
		public string DIACHILAMVIEC
		{
			get
			{
				return this._DIACHILAMVIEC;
			}
			set
			{
				if ((this._DIACHILAMVIEC != value))
				{
					this.OnDIACHILAMVIECChanging(value);
					this.SendPropertyChanging();
					this._DIACHILAMVIEC = value;
					this.SendPropertyChanged("DIACHILAMVIEC");
					this.OnDIACHILAMVIECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHANHPHO", DbType="Int")]
		public System.Nullable<int> MATHANHPHO
		{
			get
			{
				return this._MATHANHPHO;
			}
			set
			{
				if ((this._MATHANHPHO != value))
				{
					if (this._THANHPHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHANHPHOChanging(value);
					this.SendPropertyChanging();
					this._MATHANHPHO = value;
					this.SendPropertyChanged("MATHANHPHO");
					this.OnMATHANHPHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUCLUONGTOITHIEU", DbType="Float")]
		public System.Nullable<double> MUCLUONGTOITHIEU
		{
			get
			{
				return this._MUCLUONGTOITHIEU;
			}
			set
			{
				if ((this._MUCLUONGTOITHIEU != value))
				{
					this.OnMUCLUONGTOITHIEUChanging(value);
					this.SendPropertyChanging();
					this._MUCLUONGTOITHIEU = value;
					this.SendPropertyChanged("MUCLUONGTOITHIEU");
					this.OnMUCLUONGTOITHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUCLUONGTOIDA", DbType="Float")]
		public System.Nullable<double> MUCLUONGTOIDA
		{
			get
			{
				return this._MUCLUONGTOIDA;
			}
			set
			{
				if ((this._MUCLUONGTOIDA != value))
				{
					this.OnMUCLUONGTOIDAChanging(value);
					this.SendPropertyChanging();
					this._MUCLUONGTOIDA = value;
					this.SendPropertyChanged("MUCLUONGTOIDA");
					this.OnMUCLUONGTOIDAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOTACV", DbType="NVarChar(50)")]
		public string MOTACV
		{
			get
			{
				return this._MOTACV;
			}
			set
			{
				if ((this._MOTACV != value))
				{
					this.OnMOTACVChanging(value);
					this.SendPropertyChanging();
					this._MOTACV = value;
					this.SendPropertyChanged("MOTACV");
					this.OnMOTACVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YEUCAUCV", DbType="NVarChar(100)")]
		public string YEUCAUCV
		{
			get
			{
				return this._YEUCAUCV;
			}
			set
			{
				if ((this._YEUCAUCV != value))
				{
					this.OnYEUCAUCVChanging(value);
					this.SendPropertyChanging();
					this._YEUCAUCV = value;
					this.SendPropertyChanged("YEUCAUCV");
					this.OnYEUCAUCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KYNANG", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KYNANG
		{
			get
			{
				return this._KYNANG;
			}
			set
			{
				if ((this._KYNANG != value))
				{
					this.OnKYNANGChanging(value);
					this.SendPropertyChanging();
					this._KYNANG = value;
					this.SendPropertyChanged("KYNANG");
					this.OnKYNANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUOILIENHE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NGUOILIENHE
		{
			get
			{
				return this._NGUOILIENHE;
			}
			set
			{
				if ((this._NGUOILIENHE != value))
				{
					this.OnNGUOILIENHEChanging(value);
					this.SendPropertyChanging();
					this._NGUOILIENHE = value;
					this.SendPropertyChanged("NGUOILIENHE");
					this.OnNGUOILIENHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAILLIENHE", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EMAILLIENHE
		{
			get
			{
				return this._EMAILLIENHE;
			}
			set
			{
				if ((this._EMAILLIENHE != value))
				{
					this.OnEMAILLIENHEChanging(value);
					this.SendPropertyChanging();
					this._EMAILLIENHE = value;
					this.SendPropertyChanged("EMAILLIENHE");
					this.OnEMAILLIENHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_CHITIETTUYENDUNG", Storage="_NGANH", ThisKey="MANGANH", OtherKey="MANGANH", IsForeignKey=true)]
		public NGANH NGANH
		{
			get
			{
				return this._NGANH.Entity;
			}
			set
			{
				NGANH previousValue = this._NGANH.Entity;
				if (((previousValue != value) 
							|| (this._NGANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGANH.Entity = null;
						previousValue.CHITIETTUYENDUNGs.Remove(this);
					}
					this._NGANH.Entity = value;
					if ((value != null))
					{
						value.CHITIETTUYENDUNGs.Add(this);
						this._MANGANH = value.MANGANH;
					}
					else
					{
						this._MANGANH = default(int);
					}
					this.SendPropertyChanged("NGANH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDANGTUYEN_CHITIETTUYENDUNG", Storage="_PHIEUDANGTUYEN", ThisKey="MAPDT", OtherKey="MAPDT", IsForeignKey=true)]
		public PHIEUDANGTUYEN PHIEUDANGTUYEN
		{
			get
			{
				return this._PHIEUDANGTUYEN.Entity;
			}
			set
			{
				PHIEUDANGTUYEN previousValue = this._PHIEUDANGTUYEN.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUDANGTUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDANGTUYEN.Entity = null;
						previousValue.CHITIETTUYENDUNG = null;
					}
					this._PHIEUDANGTUYEN.Entity = value;
					if ((value != null))
					{
						value.CHITIETTUYENDUNG = this;
						this._MAPDT = value.MAPDT;
					}
					else
					{
						this._MAPDT = default(int);
					}
					this.SendPropertyChanged("PHIEUDANGTUYEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHPHO_CHITIETTUYENDUNG", Storage="_THANHPHO", ThisKey="MATHANHPHO", OtherKey="MATHANHPHO", IsForeignKey=true)]
		public THANHPHO THANHPHO
		{
			get
			{
				return this._THANHPHO.Entity;
			}
			set
			{
				THANHPHO previousValue = this._THANHPHO.Entity;
				if (((previousValue != value) 
							|| (this._THANHPHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANHPHO.Entity = null;
						previousValue.CHITIETTUYENDUNGs.Remove(this);
					}
					this._THANHPHO.Entity = value;
					if ((value != null))
					{
						value.CHITIETTUYENDUNGs.Add(this);
						this._MATHANHPHO = value.MATHANHPHO;
					}
					else
					{
						this._MATHANHPHO = default(Nullable<int>);
					}
					this.SendPropertyChanged("THANHPHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTINCANHAN")]
	public partial class THONGTINCANHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATKCN;
		
		private string _HO;
		
		private string _TEN;
		
		private string _GIOITINH;
		
		private System.DateTime _NGAYSINH;
		
		private string _SDT;
		
		private string _DIACHI;
		
		private System.Nullable<int> _MATHANHPHO;
		
		private EntityRef<TAIKHOAN_CN> _TAIKHOAN_CN;
		
		private EntityRef<THANHPHO> _THANHPHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATKCNChanging(int value);
    partial void OnMATKCNChanged();
    partial void OnHOChanging(string value);
    partial void OnHOChanged();
    partial void OnTENChanging(string value);
    partial void OnTENChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnNGAYSINHChanging(System.DateTime value);
    partial void OnNGAYSINHChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnMATHANHPHOChanging(System.Nullable<int> value);
    partial void OnMATHANHPHOChanged();
    #endregion
		
		public THONGTINCANHAN()
		{
			this._TAIKHOAN_CN = default(EntityRef<TAIKHOAN_CN>);
			this._THANHPHO = default(EntityRef<THANHPHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKCN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MATKCN
		{
			get
			{
				return this._MATKCN;
			}
			set
			{
				if ((this._MATKCN != value))
				{
					if (this._TAIKHOAN_CN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATKCNChanging(value);
					this.SendPropertyChanging();
					this._MATKCN = value;
					this.SendPropertyChanged("MATKCN");
					this.OnMATKCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HO", DbType="NVarChar(50)")]
		public string HO
		{
			get
			{
				return this._HO;
			}
			set
			{
				if ((this._HO != value))
				{
					this.OnHOChanging(value);
					this.SendPropertyChanging();
					this._HO = value;
					this.SendPropertyChanged("HO");
					this.OnHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN", DbType="NVarChar(20)")]
		public string TEN
		{
			get
			{
				return this._TEN;
			}
			set
			{
				if ((this._TEN != value))
				{
					this.OnTENChanging(value);
					this.SendPropertyChanging();
					this._TEN = value;
					this.SendPropertyChanged("TEN");
					this.OnTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="SmallDateTime NOT NULL")]
		public System.DateTime NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(12)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHANHPHO", DbType="Int")]
		public System.Nullable<int> MATHANHPHO
		{
			get
			{
				return this._MATHANHPHO;
			}
			set
			{
				if ((this._MATHANHPHO != value))
				{
					if (this._THANHPHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHANHPHOChanging(value);
					this.SendPropertyChanging();
					this._MATHANHPHO = value;
					this.SendPropertyChanged("MATHANHPHO");
					this.OnMATHANHPHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_CN_THONGTINCANHAN", Storage="_TAIKHOAN_CN", ThisKey="MATKCN", OtherKey="MATKCN", IsForeignKey=true)]
		public TAIKHOAN_CN TAIKHOAN_CN
		{
			get
			{
				return this._TAIKHOAN_CN.Entity;
			}
			set
			{
				TAIKHOAN_CN previousValue = this._TAIKHOAN_CN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN_CN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN_CN.Entity = null;
						previousValue.THONGTINCANHAN = null;
					}
					this._TAIKHOAN_CN.Entity = value;
					if ((value != null))
					{
						value.THONGTINCANHAN = this;
						this._MATKCN = value.MATKCN;
					}
					else
					{
						this._MATKCN = default(int);
					}
					this.SendPropertyChanged("TAIKHOAN_CN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHPHO_THONGTINCANHAN", Storage="_THANHPHO", ThisKey="MATHANHPHO", OtherKey="MATHANHPHO", IsForeignKey=true)]
		public THANHPHO THANHPHO
		{
			get
			{
				return this._THANHPHO.Entity;
			}
			set
			{
				THANHPHO previousValue = this._THANHPHO.Entity;
				if (((previousValue != value) 
							|| (this._THANHPHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANHPHO.Entity = null;
						previousValue.THONGTINCANHANs.Remove(this);
					}
					this._THANHPHO.Entity = value;
					if ((value != null))
					{
						value.THONGTINCANHANs.Add(this);
						this._MATHANHPHO = value.MATHANHPHO;
					}
					else
					{
						this._MATHANHPHO = default(Nullable<int>);
					}
					this.SendPropertyChanged("THANHPHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOSOXINVIEC")]
	public partial class HOSOXINVIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATKCN;
		
		private System.Nullable<int> _MANGANH;
		
		private string _HOCVAN;
		
		private string _KINHNGHIEM;
		
		private string _KYNANG;
		
		private System.Nullable<int> _MANGOAINGU;
		
		private EntityRef<NGANH> _NGANH;
		
		private EntityRef<NGOAINGU> _NGOAINGU;
		
		private EntityRef<TAIKHOAN_CN> _TAIKHOAN_CN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATKCNChanging(int value);
    partial void OnMATKCNChanged();
    partial void OnMANGANHChanging(System.Nullable<int> value);
    partial void OnMANGANHChanged();
    partial void OnHOCVANChanging(string value);
    partial void OnHOCVANChanged();
    partial void OnKINHNGHIEMChanging(string value);
    partial void OnKINHNGHIEMChanged();
    partial void OnKYNANGChanging(string value);
    partial void OnKYNANGChanged();
    partial void OnMANGOAINGUChanging(System.Nullable<int> value);
    partial void OnMANGOAINGUChanged();
    #endregion
		
		public HOSOXINVIEC()
		{
			this._NGANH = default(EntityRef<NGANH>);
			this._NGOAINGU = default(EntityRef<NGOAINGU>);
			this._TAIKHOAN_CN = default(EntityRef<TAIKHOAN_CN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKCN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MATKCN
		{
			get
			{
				return this._MATKCN;
			}
			set
			{
				if ((this._MATKCN != value))
				{
					if (this._TAIKHOAN_CN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATKCNChanging(value);
					this.SendPropertyChanging();
					this._MATKCN = value;
					this.SendPropertyChanged("MATKCN");
					this.OnMATKCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGANH", DbType="Int")]
		public System.Nullable<int> MANGANH
		{
			get
			{
				return this._MANGANH;
			}
			set
			{
				if ((this._MANGANH != value))
				{
					if (this._NGANH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANGANHChanging(value);
					this.SendPropertyChanging();
					this._MANGANH = value;
					this.SendPropertyChanged("MANGANH");
					this.OnMANGANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOCVAN", DbType="NVarChar(100)")]
		public string HOCVAN
		{
			get
			{
				return this._HOCVAN;
			}
			set
			{
				if ((this._HOCVAN != value))
				{
					this.OnHOCVANChanging(value);
					this.SendPropertyChanging();
					this._HOCVAN = value;
					this.SendPropertyChanged("HOCVAN");
					this.OnHOCVANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KINHNGHIEM", DbType="NVarChar(MAX)")]
		public string KINHNGHIEM
		{
			get
			{
				return this._KINHNGHIEM;
			}
			set
			{
				if ((this._KINHNGHIEM != value))
				{
					this.OnKINHNGHIEMChanging(value);
					this.SendPropertyChanging();
					this._KINHNGHIEM = value;
					this.SendPropertyChanged("KINHNGHIEM");
					this.OnKINHNGHIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KYNANG", DbType="NVarChar(MAX)")]
		public string KYNANG
		{
			get
			{
				return this._KYNANG;
			}
			set
			{
				if ((this._KYNANG != value))
				{
					this.OnKYNANGChanging(value);
					this.SendPropertyChanging();
					this._KYNANG = value;
					this.SendPropertyChanged("KYNANG");
					this.OnKYNANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGOAINGU", DbType="Int")]
		public System.Nullable<int> MANGOAINGU
		{
			get
			{
				return this._MANGOAINGU;
			}
			set
			{
				if ((this._MANGOAINGU != value))
				{
					if (this._NGOAINGU.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANGOAINGUChanging(value);
					this.SendPropertyChanging();
					this._MANGOAINGU = value;
					this.SendPropertyChanged("MANGOAINGU");
					this.OnMANGOAINGUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_HOSOXINVIEC", Storage="_NGANH", ThisKey="MANGANH", OtherKey="MANGANH", IsForeignKey=true)]
		public NGANH NGANH
		{
			get
			{
				return this._NGANH.Entity;
			}
			set
			{
				NGANH previousValue = this._NGANH.Entity;
				if (((previousValue != value) 
							|| (this._NGANH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGANH.Entity = null;
						previousValue.HOSOXINVIECs.Remove(this);
					}
					this._NGANH.Entity = value;
					if ((value != null))
					{
						value.HOSOXINVIECs.Add(this);
						this._MANGANH = value.MANGANH;
					}
					else
					{
						this._MANGANH = default(Nullable<int>);
					}
					this.SendPropertyChanged("NGANH");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGOAINGU_HOSOXINVIEC", Storage="_NGOAINGU", ThisKey="MANGOAINGU", OtherKey="MANGOAINGU", IsForeignKey=true)]
		public NGOAINGU NGOAINGU
		{
			get
			{
				return this._NGOAINGU.Entity;
			}
			set
			{
				NGOAINGU previousValue = this._NGOAINGU.Entity;
				if (((previousValue != value) 
							|| (this._NGOAINGU.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NGOAINGU.Entity = null;
						previousValue.HOSOXINVIECs.Remove(this);
					}
					this._NGOAINGU.Entity = value;
					if ((value != null))
					{
						value.HOSOXINVIECs.Add(this);
						this._MANGOAINGU = value.MANGOAINGU;
					}
					else
					{
						this._MANGOAINGU = default(Nullable<int>);
					}
					this.SendPropertyChanged("NGOAINGU");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_CN_HOSOXINVIEC", Storage="_TAIKHOAN_CN", ThisKey="MATKCN", OtherKey="MATKCN", IsForeignKey=true)]
		public TAIKHOAN_CN TAIKHOAN_CN
		{
			get
			{
				return this._TAIKHOAN_CN.Entity;
			}
			set
			{
				TAIKHOAN_CN previousValue = this._TAIKHOAN_CN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN_CN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN_CN.Entity = null;
						previousValue.HOSOXINVIEC = null;
					}
					this._TAIKHOAN_CN.Entity = value;
					if ((value != null))
					{
						value.HOSOXINVIEC = this;
						this._MATKCN = value.MATKCN;
					}
					else
					{
						this._MATKCN = default(int);
					}
					this.SendPropertyChanged("TAIKHOAN_CN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LUOTUNGTUYEN")]
	public partial class LUOTUNGTUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATKDN;
		
		private System.Nullable<int> _SOLUONG;
		
		private EntityRef<TAIKHOAN_DN> _TAIKHOAN_DN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATKDNChanging(int value);
    partial void OnMATKDNChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    #endregion
		
		public LUOTUNGTUYEN()
		{
			this._TAIKHOAN_DN = default(EntityRef<TAIKHOAN_DN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKDN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MATKDN
		{
			get
			{
				return this._MATKDN;
			}
			set
			{
				if ((this._MATKDN != value))
				{
					if (this._TAIKHOAN_DN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATKDNChanging(value);
					this.SendPropertyChanging();
					this._MATKDN = value;
					this.SendPropertyChanged("MATKDN");
					this.OnMATKDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_DN_LUOTUNGTUYEN", Storage="_TAIKHOAN_DN", ThisKey="MATKDN", OtherKey="MATKDN", IsForeignKey=true)]
		public TAIKHOAN_DN TAIKHOAN_DN
		{
			get
			{
				return this._TAIKHOAN_DN.Entity;
			}
			set
			{
				TAIKHOAN_DN previousValue = this._TAIKHOAN_DN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN_DN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN_DN.Entity = null;
						previousValue.LUOTUNGTUYEN = null;
					}
					this._TAIKHOAN_DN.Entity = value;
					if ((value != null))
					{
						value.LUOTUNGTUYEN = this;
						this._MATKDN = value.MATKDN;
					}
					else
					{
						this._MATKDN = default(int);
					}
					this.SendPropertyChanged("TAIKHOAN_DN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NOPDON")]
	public partial class NOPDON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATKCN;
		
		private int _MAPDT;
		
		private System.Nullable<bool> _TINHTRANG;
		
		private EntityRef<PHIEUDANGTUYEN> _PHIEUDANGTUYEN;
		
		private EntityRef<TAIKHOAN_CN> _TAIKHOAN_CN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATKCNChanging(int value);
    partial void OnMATKCNChanged();
    partial void OnMAPDTChanging(int value);
    partial void OnMAPDTChanged();
    partial void OnTINHTRANGChanging(System.Nullable<bool> value);
    partial void OnTINHTRANGChanged();
    #endregion
		
		public NOPDON()
		{
			this._PHIEUDANGTUYEN = default(EntityRef<PHIEUDANGTUYEN>);
			this._TAIKHOAN_CN = default(EntityRef<TAIKHOAN_CN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKCN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MATKCN
		{
			get
			{
				return this._MATKCN;
			}
			set
			{
				if ((this._MATKCN != value))
				{
					if (this._TAIKHOAN_CN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATKCNChanging(value);
					this.SendPropertyChanging();
					this._MATKCN = value;
					this.SendPropertyChanged("MATKCN");
					this.OnMATKCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPDT", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MAPDT
		{
			get
			{
				return this._MAPDT;
			}
			set
			{
				if ((this._MAPDT != value))
				{
					if (this._PHIEUDANGTUYEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPDTChanging(value);
					this.SendPropertyChanging();
					this._MAPDT = value;
					this.SendPropertyChanged("MAPDT");
					this.OnMAPDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TINHTRANG", DbType="Bit")]
		public System.Nullable<bool> TINHTRANG
		{
			get
			{
				return this._TINHTRANG;
			}
			set
			{
				if ((this._TINHTRANG != value))
				{
					this.OnTINHTRANGChanging(value);
					this.SendPropertyChanging();
					this._TINHTRANG = value;
					this.SendPropertyChanged("TINHTRANG");
					this.OnTINHTRANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDANGTUYEN_NOPDON", Storage="_PHIEUDANGTUYEN", ThisKey="MAPDT", OtherKey="MAPDT", IsForeignKey=true)]
		public PHIEUDANGTUYEN PHIEUDANGTUYEN
		{
			get
			{
				return this._PHIEUDANGTUYEN.Entity;
			}
			set
			{
				PHIEUDANGTUYEN previousValue = this._PHIEUDANGTUYEN.Entity;
				if (((previousValue != value) 
							|| (this._PHIEUDANGTUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHIEUDANGTUYEN.Entity = null;
						previousValue.NOPDONs.Remove(this);
					}
					this._PHIEUDANGTUYEN.Entity = value;
					if ((value != null))
					{
						value.NOPDONs.Add(this);
						this._MAPDT = value.MAPDT;
					}
					else
					{
						this._MAPDT = default(int);
					}
					this.SendPropertyChanged("PHIEUDANGTUYEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_CN_NOPDON", Storage="_TAIKHOAN_CN", ThisKey="MATKCN", OtherKey="MATKCN", IsForeignKey=true)]
		public TAIKHOAN_CN TAIKHOAN_CN
		{
			get
			{
				return this._TAIKHOAN_CN.Entity;
			}
			set
			{
				TAIKHOAN_CN previousValue = this._TAIKHOAN_CN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN_CN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN_CN.Entity = null;
						previousValue.NOPDONs.Remove(this);
					}
					this._TAIKHOAN_CN.Entity = value;
					if ((value != null))
					{
						value.NOPDONs.Add(this);
						this._MATKCN = value.MATKCN;
					}
					else
					{
						this._MATKCN = default(int);
					}
					this.SendPropertyChanged("TAIKHOAN_CN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGANH")]
	public partial class NGANH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANGANH;
		
		private string _TENNGANH;
		
		private EntitySet<CHITIETTUYENDUNG> _CHITIETTUYENDUNGs;
		
		private EntitySet<HOSOXINVIEC> _HOSOXINVIECs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANGANHChanging(int value);
    partial void OnMANGANHChanged();
    partial void OnTENNGANHChanging(string value);
    partial void OnTENNGANHChanged();
    #endregion
		
		public NGANH()
		{
			this._CHITIETTUYENDUNGs = new EntitySet<CHITIETTUYENDUNG>(new Action<CHITIETTUYENDUNG>(this.attach_CHITIETTUYENDUNGs), new Action<CHITIETTUYENDUNG>(this.detach_CHITIETTUYENDUNGs));
			this._HOSOXINVIECs = new EntitySet<HOSOXINVIEC>(new Action<HOSOXINVIEC>(this.attach_HOSOXINVIECs), new Action<HOSOXINVIEC>(this.detach_HOSOXINVIECs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGANH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANGANH
		{
			get
			{
				return this._MANGANH;
			}
			set
			{
				if ((this._MANGANH != value))
				{
					this.OnMANGANHChanging(value);
					this.SendPropertyChanging();
					this._MANGANH = value;
					this.SendPropertyChanged("MANGANH");
					this.OnMANGANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNGANH", DbType="NVarChar(50)")]
		public string TENNGANH
		{
			get
			{
				return this._TENNGANH;
			}
			set
			{
				if ((this._TENNGANH != value))
				{
					this.OnTENNGANHChanging(value);
					this.SendPropertyChanging();
					this._TENNGANH = value;
					this.SendPropertyChanged("TENNGANH");
					this.OnTENNGANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_CHITIETTUYENDUNG", Storage="_CHITIETTUYENDUNGs", ThisKey="MANGANH", OtherKey="MANGANH")]
		public EntitySet<CHITIETTUYENDUNG> CHITIETTUYENDUNGs
		{
			get
			{
				return this._CHITIETTUYENDUNGs;
			}
			set
			{
				this._CHITIETTUYENDUNGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGANH_HOSOXINVIEC", Storage="_HOSOXINVIECs", ThisKey="MANGANH", OtherKey="MANGANH")]
		public EntitySet<HOSOXINVIEC> HOSOXINVIECs
		{
			get
			{
				return this._HOSOXINVIECs;
			}
			set
			{
				this._HOSOXINVIECs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETTUYENDUNGs(CHITIETTUYENDUNG entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = this;
		}
		
		private void detach_CHITIETTUYENDUNGs(CHITIETTUYENDUNG entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = null;
		}
		
		private void attach_HOSOXINVIECs(HOSOXINVIEC entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = this;
		}
		
		private void detach_HOSOXINVIECs(HOSOXINVIEC entity)
		{
			this.SendPropertyChanging();
			entity.NGANH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGOAINGU")]
	public partial class NGOAINGU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MANGOAINGU;
		
		private string _TENNGOAINGU;
		
		private string _TRINHDO;
		
		private EntitySet<HOSOXINVIEC> _HOSOXINVIECs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANGOAINGUChanging(int value);
    partial void OnMANGOAINGUChanged();
    partial void OnTENNGOAINGUChanging(string value);
    partial void OnTENNGOAINGUChanged();
    partial void OnTRINHDOChanging(string value);
    partial void OnTRINHDOChanged();
    #endregion
		
		public NGOAINGU()
		{
			this._HOSOXINVIECs = new EntitySet<HOSOXINVIEC>(new Action<HOSOXINVIEC>(this.attach_HOSOXINVIECs), new Action<HOSOXINVIEC>(this.detach_HOSOXINVIECs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANGOAINGU", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MANGOAINGU
		{
			get
			{
				return this._MANGOAINGU;
			}
			set
			{
				if ((this._MANGOAINGU != value))
				{
					this.OnMANGOAINGUChanging(value);
					this.SendPropertyChanging();
					this._MANGOAINGU = value;
					this.SendPropertyChanged("MANGOAINGU");
					this.OnMANGOAINGUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENNGOAINGU", DbType="VarChar(30)")]
		public string TENNGOAINGU
		{
			get
			{
				return this._TENNGOAINGU;
			}
			set
			{
				if ((this._TENNGOAINGU != value))
				{
					this.OnTENNGOAINGUChanging(value);
					this.SendPropertyChanging();
					this._TENNGOAINGU = value;
					this.SendPropertyChanged("TENNGOAINGU");
					this.OnTENNGOAINGUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRINHDO", DbType="NVarChar(10)")]
		public string TRINHDO
		{
			get
			{
				return this._TRINHDO;
			}
			set
			{
				if ((this._TRINHDO != value))
				{
					this.OnTRINHDOChanging(value);
					this.SendPropertyChanging();
					this._TRINHDO = value;
					this.SendPropertyChanged("TRINHDO");
					this.OnTRINHDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NGOAINGU_HOSOXINVIEC", Storage="_HOSOXINVIECs", ThisKey="MANGOAINGU", OtherKey="MANGOAINGU")]
		public EntitySet<HOSOXINVIEC> HOSOXINVIECs
		{
			get
			{
				return this._HOSOXINVIECs;
			}
			set
			{
				this._HOSOXINVIECs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOSOXINVIECs(HOSOXINVIEC entity)
		{
			this.SendPropertyChanging();
			entity.NGOAINGU = this;
		}
		
		private void detach_HOSOXINVIECs(HOSOXINVIEC entity)
		{
			this.SendPropertyChanging();
			entity.NGOAINGU = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIEUDANGTUYEN")]
	public partial class PHIEUDANGTUYEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MAPDT;
		
		private System.Nullable<int> _MATKDN;
		
		private System.Nullable<System.DateTime> _NGAYDANGTIN;
		
		private System.Nullable<System.DateTime> _THOIHANDANGTIN;
		
		private EntityRef<CHITIETTUYENDUNG> _CHITIETTUYENDUNG;
		
		private EntitySet<NOPDON> _NOPDONs;
		
		private EntityRef<TAIKHOAN_DN> _TAIKHOAN_DN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPDTChanging(int value);
    partial void OnMAPDTChanged();
    partial void OnMATKDNChanging(System.Nullable<int> value);
    partial void OnMATKDNChanged();
    partial void OnNGAYDANGTINChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYDANGTINChanged();
    partial void OnTHOIHANDANGTINChanging(System.Nullable<System.DateTime> value);
    partial void OnTHOIHANDANGTINChanged();
    #endregion
		
		public PHIEUDANGTUYEN()
		{
			this._CHITIETTUYENDUNG = default(EntityRef<CHITIETTUYENDUNG>);
			this._NOPDONs = new EntitySet<NOPDON>(new Action<NOPDON>(this.attach_NOPDONs), new Action<NOPDON>(this.detach_NOPDONs));
			this._TAIKHOAN_DN = default(EntityRef<TAIKHOAN_DN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPDT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MAPDT
		{
			get
			{
				return this._MAPDT;
			}
			set
			{
				if ((this._MAPDT != value))
				{
					this.OnMAPDTChanging(value);
					this.SendPropertyChanging();
					this._MAPDT = value;
					this.SendPropertyChanged("MAPDT");
					this.OnMAPDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKDN", DbType="Int")]
		public System.Nullable<int> MATKDN
		{
			get
			{
				return this._MATKDN;
			}
			set
			{
				if ((this._MATKDN != value))
				{
					if (this._TAIKHOAN_DN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATKDNChanging(value);
					this.SendPropertyChanging();
					this._MATKDN = value;
					this.SendPropertyChanged("MATKDN");
					this.OnMATKDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYDANGTIN", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAYDANGTIN
		{
			get
			{
				return this._NGAYDANGTIN;
			}
			set
			{
				if ((this._NGAYDANGTIN != value))
				{
					this.OnNGAYDANGTINChanging(value);
					this.SendPropertyChanging();
					this._NGAYDANGTIN = value;
					this.SendPropertyChanged("NGAYDANGTIN");
					this.OnNGAYDANGTINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIHANDANGTIN", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> THOIHANDANGTIN
		{
			get
			{
				return this._THOIHANDANGTIN;
			}
			set
			{
				if ((this._THOIHANDANGTIN != value))
				{
					this.OnTHOIHANDANGTINChanging(value);
					this.SendPropertyChanging();
					this._THOIHANDANGTIN = value;
					this.SendPropertyChanged("THOIHANDANGTIN");
					this.OnTHOIHANDANGTINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDANGTUYEN_CHITIETTUYENDUNG", Storage="_CHITIETTUYENDUNG", ThisKey="MAPDT", OtherKey="MAPDT", IsUnique=true, IsForeignKey=false)]
		public CHITIETTUYENDUNG CHITIETTUYENDUNG
		{
			get
			{
				return this._CHITIETTUYENDUNG.Entity;
			}
			set
			{
				CHITIETTUYENDUNG previousValue = this._CHITIETTUYENDUNG.Entity;
				if (((previousValue != value) 
							|| (this._CHITIETTUYENDUNG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHITIETTUYENDUNG.Entity = null;
						previousValue.PHIEUDANGTUYEN = null;
					}
					this._CHITIETTUYENDUNG.Entity = value;
					if ((value != null))
					{
						value.PHIEUDANGTUYEN = this;
					}
					this.SendPropertyChanged("CHITIETTUYENDUNG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIEUDANGTUYEN_NOPDON", Storage="_NOPDONs", ThisKey="MAPDT", OtherKey="MAPDT")]
		public EntitySet<NOPDON> NOPDONs
		{
			get
			{
				return this._NOPDONs;
			}
			set
			{
				this._NOPDONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_DN_PHIEUDANGTUYEN", Storage="_TAIKHOAN_DN", ThisKey="MATKDN", OtherKey="MATKDN", IsForeignKey=true)]
		public TAIKHOAN_DN TAIKHOAN_DN
		{
			get
			{
				return this._TAIKHOAN_DN.Entity;
			}
			set
			{
				TAIKHOAN_DN previousValue = this._TAIKHOAN_DN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN_DN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN_DN.Entity = null;
						previousValue.PHIEUDANGTUYENs.Remove(this);
					}
					this._TAIKHOAN_DN.Entity = value;
					if ((value != null))
					{
						value.PHIEUDANGTUYENs.Add(this);
						this._MATKDN = value.MATKDN;
					}
					else
					{
						this._MATKDN = default(Nullable<int>);
					}
					this.SendPropertyChanged("TAIKHOAN_DN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NOPDONs(NOPDON entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDANGTUYEN = this;
		}
		
		private void detach_NOPDONs(NOPDON entity)
		{
			this.SendPropertyChanging();
			entity.PHIEUDANGTUYEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN_CN")]
	public partial class TAIKHOAN_CN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATKCN;
		
		private string _MASV;
		
		private string _PASS;
		
		private EntityRef<THONGTINCANHAN> _THONGTINCANHAN;
		
		private EntityRef<HOSOXINVIEC> _HOSOXINVIEC;
		
		private EntitySet<NOPDON> _NOPDONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATKCNChanging(int value);
    partial void OnMATKCNChanged();
    partial void OnMASVChanging(string value);
    partial void OnMASVChanged();
    partial void OnPASSChanging(string value);
    partial void OnPASSChanged();
    #endregion
		
		public TAIKHOAN_CN()
		{
			this._THONGTINCANHAN = default(EntityRef<THONGTINCANHAN>);
			this._HOSOXINVIEC = default(EntityRef<HOSOXINVIEC>);
			this._NOPDONs = new EntitySet<NOPDON>(new Action<NOPDON>(this.attach_NOPDONs), new Action<NOPDON>(this.detach_NOPDONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKCN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATKCN
		{
			get
			{
				return this._MATKCN;
			}
			set
			{
				if ((this._MATKCN != value))
				{
					this.OnMATKCNChanging(value);
					this.SendPropertyChanging();
					this._MATKCN = value;
					this.SendPropertyChanged("MATKCN");
					this.OnMATKCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MASV", DbType="Char(11)")]
		public string MASV
		{
			get
			{
				return this._MASV;
			}
			set
			{
				if ((this._MASV != value))
				{
					this.OnMASVChanging(value);
					this.SendPropertyChanging();
					this._MASV = value;
					this.SendPropertyChanged("MASV");
					this.OnMASVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS", DbType="NVarChar(30)")]
		public string PASS
		{
			get
			{
				return this._PASS;
			}
			set
			{
				if ((this._PASS != value))
				{
					this.OnPASSChanging(value);
					this.SendPropertyChanging();
					this._PASS = value;
					this.SendPropertyChanged("PASS");
					this.OnPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_CN_THONGTINCANHAN", Storage="_THONGTINCANHAN", ThisKey="MATKCN", OtherKey="MATKCN", IsUnique=true, IsForeignKey=false)]
		public THONGTINCANHAN THONGTINCANHAN
		{
			get
			{
				return this._THONGTINCANHAN.Entity;
			}
			set
			{
				THONGTINCANHAN previousValue = this._THONGTINCANHAN.Entity;
				if (((previousValue != value) 
							|| (this._THONGTINCANHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THONGTINCANHAN.Entity = null;
						previousValue.TAIKHOAN_CN = null;
					}
					this._THONGTINCANHAN.Entity = value;
					if ((value != null))
					{
						value.TAIKHOAN_CN = this;
					}
					this.SendPropertyChanged("THONGTINCANHAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_CN_HOSOXINVIEC", Storage="_HOSOXINVIEC", ThisKey="MATKCN", OtherKey="MATKCN", IsUnique=true, IsForeignKey=false)]
		public HOSOXINVIEC HOSOXINVIEC
		{
			get
			{
				return this._HOSOXINVIEC.Entity;
			}
			set
			{
				HOSOXINVIEC previousValue = this._HOSOXINVIEC.Entity;
				if (((previousValue != value) 
							|| (this._HOSOXINVIEC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOSOXINVIEC.Entity = null;
						previousValue.TAIKHOAN_CN = null;
					}
					this._HOSOXINVIEC.Entity = value;
					if ((value != null))
					{
						value.TAIKHOAN_CN = this;
					}
					this.SendPropertyChanged("HOSOXINVIEC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_CN_NOPDON", Storage="_NOPDONs", ThisKey="MATKCN", OtherKey="MATKCN")]
		public EntitySet<NOPDON> NOPDONs
		{
			get
			{
				return this._NOPDONs;
			}
			set
			{
				this._NOPDONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NOPDONs(NOPDON entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN_CN = this;
		}
		
		private void detach_NOPDONs(NOPDON entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN_CN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN_DN")]
	public partial class TAIKHOAN_DN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATKDN;
		
		private string _EMAIL;
		
		private string _PASS;
		
		private EntityRef<LUOTUNGTUYEN> _LUOTUNGTUYEN;
		
		private EntitySet<PHIEUDANGTUYEN> _PHIEUDANGTUYENs;
		
		private EntityRef<TTDOANHNGHIEP> _TTDOANHNGHIEP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATKDNChanging(int value);
    partial void OnMATKDNChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnPASSChanging(string value);
    partial void OnPASSChanged();
    #endregion
		
		public TAIKHOAN_DN()
		{
			this._LUOTUNGTUYEN = default(EntityRef<LUOTUNGTUYEN>);
			this._PHIEUDANGTUYENs = new EntitySet<PHIEUDANGTUYEN>(new Action<PHIEUDANGTUYEN>(this.attach_PHIEUDANGTUYENs), new Action<PHIEUDANGTUYEN>(this.detach_PHIEUDANGTUYENs));
			this._TTDOANHNGHIEP = default(EntityRef<TTDOANHNGHIEP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKDN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATKDN
		{
			get
			{
				return this._MATKDN;
			}
			set
			{
				if ((this._MATKDN != value))
				{
					this.OnMATKDNChanging(value);
					this.SendPropertyChanging();
					this._MATKDN = value;
					this.SendPropertyChanged("MATKDN");
					this.OnMATKDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(30)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PASS", DbType="NVarChar(30)")]
		public string PASS
		{
			get
			{
				return this._PASS;
			}
			set
			{
				if ((this._PASS != value))
				{
					this.OnPASSChanging(value);
					this.SendPropertyChanging();
					this._PASS = value;
					this.SendPropertyChanged("PASS");
					this.OnPASSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_DN_LUOTUNGTUYEN", Storage="_LUOTUNGTUYEN", ThisKey="MATKDN", OtherKey="MATKDN", IsUnique=true, IsForeignKey=false)]
		public LUOTUNGTUYEN LUOTUNGTUYEN
		{
			get
			{
				return this._LUOTUNGTUYEN.Entity;
			}
			set
			{
				LUOTUNGTUYEN previousValue = this._LUOTUNGTUYEN.Entity;
				if (((previousValue != value) 
							|| (this._LUOTUNGTUYEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LUOTUNGTUYEN.Entity = null;
						previousValue.TAIKHOAN_DN = null;
					}
					this._LUOTUNGTUYEN.Entity = value;
					if ((value != null))
					{
						value.TAIKHOAN_DN = this;
					}
					this.SendPropertyChanged("LUOTUNGTUYEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_DN_PHIEUDANGTUYEN", Storage="_PHIEUDANGTUYENs", ThisKey="MATKDN", OtherKey="MATKDN")]
		public EntitySet<PHIEUDANGTUYEN> PHIEUDANGTUYENs
		{
			get
			{
				return this._PHIEUDANGTUYENs;
			}
			set
			{
				this._PHIEUDANGTUYENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_DN_TTDOANHNGHIEP", Storage="_TTDOANHNGHIEP", ThisKey="MATKDN", OtherKey="MATKDN", IsUnique=true, IsForeignKey=false)]
		public TTDOANHNGHIEP TTDOANHNGHIEP
		{
			get
			{
				return this._TTDOANHNGHIEP.Entity;
			}
			set
			{
				TTDOANHNGHIEP previousValue = this._TTDOANHNGHIEP.Entity;
				if (((previousValue != value) 
							|| (this._TTDOANHNGHIEP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TTDOANHNGHIEP.Entity = null;
						previousValue.TAIKHOAN_DN = null;
					}
					this._TTDOANHNGHIEP.Entity = value;
					if ((value != null))
					{
						value.TAIKHOAN_DN = this;
					}
					this.SendPropertyChanged("TTDOANHNGHIEP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHIEUDANGTUYENs(PHIEUDANGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN_DN = this;
		}
		
		private void detach_PHIEUDANGTUYENs(PHIEUDANGTUYEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN_DN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TTDOANHNGHIEP")]
	public partial class TTDOANHNGHIEP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATKDN;
		
		private string _LOGO;
		
		private string _TENDN;
		
		private System.Nullable<int> _QUYMODN;
		
		private string _THONGTINDN;
		
		private string _DIACHI;
		
		private System.Nullable<int> _MATHANHPHO;
		
		private string _PHUCLOIDN;
		
		private EntityRef<TAIKHOAN_DN> _TAIKHOAN_DN;
		
		private EntityRef<THANHPHO> _THANHPHO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATKDNChanging(int value);
    partial void OnMATKDNChanged();
    partial void OnLOGOChanging(string value);
    partial void OnLOGOChanged();
    partial void OnTENDNChanging(string value);
    partial void OnTENDNChanged();
    partial void OnQUYMODNChanging(System.Nullable<int> value);
    partial void OnQUYMODNChanged();
    partial void OnTHONGTINDNChanging(string value);
    partial void OnTHONGTINDNChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnMATHANHPHOChanging(System.Nullable<int> value);
    partial void OnMATHANHPHOChanged();
    partial void OnPHUCLOIDNChanging(string value);
    partial void OnPHUCLOIDNChanged();
    #endregion
		
		public TTDOANHNGHIEP()
		{
			this._TAIKHOAN_DN = default(EntityRef<TAIKHOAN_DN>);
			this._THANHPHO = default(EntityRef<THANHPHO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKDN", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MATKDN
		{
			get
			{
				return this._MATKDN;
			}
			set
			{
				if ((this._MATKDN != value))
				{
					if (this._TAIKHOAN_DN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATKDNChanging(value);
					this.SendPropertyChanging();
					this._MATKDN = value;
					this.SendPropertyChanged("MATKDN");
					this.OnMATKDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGO", DbType="VarChar(100)")]
		public string LOGO
		{
			get
			{
				return this._LOGO;
			}
			set
			{
				if ((this._LOGO != value))
				{
					this.OnLOGOChanging(value);
					this.SendPropertyChanging();
					this._LOGO = value;
					this.SendPropertyChanged("LOGO");
					this.OnLOGOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TENDN
		{
			get
			{
				return this._TENDN;
			}
			set
			{
				if ((this._TENDN != value))
				{
					this.OnTENDNChanging(value);
					this.SendPropertyChanging();
					this._TENDN = value;
					this.SendPropertyChanged("TENDN");
					this.OnTENDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYMODN", DbType="Int")]
		public System.Nullable<int> QUYMODN
		{
			get
			{
				return this._QUYMODN;
			}
			set
			{
				if ((this._QUYMODN != value))
				{
					this.OnQUYMODNChanging(value);
					this.SendPropertyChanging();
					this._QUYMODN = value;
					this.SendPropertyChanged("QUYMODN");
					this.OnQUYMODNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THONGTINDN", DbType="NVarChar(MAX)")]
		public string THONGTINDN
		{
			get
			{
				return this._THONGTINDN;
			}
			set
			{
				if ((this._THONGTINDN != value))
				{
					this.OnTHONGTINDNChanging(value);
					this.SendPropertyChanging();
					this._THONGTINDN = value;
					this.SendPropertyChanged("THONGTINDN");
					this.OnTHONGTINDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(100)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHANHPHO", DbType="Int")]
		public System.Nullable<int> MATHANHPHO
		{
			get
			{
				return this._MATHANHPHO;
			}
			set
			{
				if ((this._MATHANHPHO != value))
				{
					if (this._THANHPHO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATHANHPHOChanging(value);
					this.SendPropertyChanging();
					this._MATHANHPHO = value;
					this.SendPropertyChanged("MATHANHPHO");
					this.OnMATHANHPHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHUCLOIDN", DbType="NVarChar(100)")]
		public string PHUCLOIDN
		{
			get
			{
				return this._PHUCLOIDN;
			}
			set
			{
				if ((this._PHUCLOIDN != value))
				{
					this.OnPHUCLOIDNChanging(value);
					this.SendPropertyChanging();
					this._PHUCLOIDN = value;
					this.SendPropertyChanged("PHUCLOIDN");
					this.OnPHUCLOIDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_DN_TTDOANHNGHIEP", Storage="_TAIKHOAN_DN", ThisKey="MATKDN", OtherKey="MATKDN", IsForeignKey=true)]
		public TAIKHOAN_DN TAIKHOAN_DN
		{
			get
			{
				return this._TAIKHOAN_DN.Entity;
			}
			set
			{
				TAIKHOAN_DN previousValue = this._TAIKHOAN_DN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN_DN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN_DN.Entity = null;
						previousValue.TTDOANHNGHIEP = null;
					}
					this._TAIKHOAN_DN.Entity = value;
					if ((value != null))
					{
						value.TTDOANHNGHIEP = this;
						this._MATKDN = value.MATKDN;
					}
					else
					{
						this._MATKDN = default(int);
					}
					this.SendPropertyChanged("TAIKHOAN_DN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHPHO_TTDOANHNGHIEP", Storage="_THANHPHO", ThisKey="MATHANHPHO", OtherKey="MATHANHPHO", IsForeignKey=true)]
		public THANHPHO THANHPHO
		{
			get
			{
				return this._THANHPHO.Entity;
			}
			set
			{
				THANHPHO previousValue = this._THANHPHO.Entity;
				if (((previousValue != value) 
							|| (this._THANHPHO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANHPHO.Entity = null;
						previousValue.TTDOANHNGHIEPs.Remove(this);
					}
					this._THANHPHO.Entity = value;
					if ((value != null))
					{
						value.TTDOANHNGHIEPs.Add(this);
						this._MATHANHPHO = value.MATHANHPHO;
					}
					else
					{
						this._MATHANHPHO = default(Nullable<int>);
					}
					this.SendPropertyChanged("THANHPHO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANHPHO")]
	public partial class THANHPHO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MATHANHPHO;
		
		private string _TENTHANHPHO;
		
		private EntitySet<CHITIETTUYENDUNG> _CHITIETTUYENDUNGs;
		
		private EntitySet<THONGTINCANHAN> _THONGTINCANHANs;
		
		private EntitySet<TTDOANHNGHIEP> _TTDOANHNGHIEPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATHANHPHOChanging(int value);
    partial void OnMATHANHPHOChanged();
    partial void OnTENTHANHPHOChanging(string value);
    partial void OnTENTHANHPHOChanged();
    #endregion
		
		public THANHPHO()
		{
			this._CHITIETTUYENDUNGs = new EntitySet<CHITIETTUYENDUNG>(new Action<CHITIETTUYENDUNG>(this.attach_CHITIETTUYENDUNGs), new Action<CHITIETTUYENDUNG>(this.detach_CHITIETTUYENDUNGs));
			this._THONGTINCANHANs = new EntitySet<THONGTINCANHAN>(new Action<THONGTINCANHAN>(this.attach_THONGTINCANHANs), new Action<THONGTINCANHAN>(this.detach_THONGTINCANHANs));
			this._TTDOANHNGHIEPs = new EntitySet<TTDOANHNGHIEP>(new Action<TTDOANHNGHIEP>(this.attach_TTDOANHNGHIEPs), new Action<TTDOANHNGHIEP>(this.detach_TTDOANHNGHIEPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATHANHPHO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MATHANHPHO
		{
			get
			{
				return this._MATHANHPHO;
			}
			set
			{
				if ((this._MATHANHPHO != value))
				{
					this.OnMATHANHPHOChanging(value);
					this.SendPropertyChanging();
					this._MATHANHPHO = value;
					this.SendPropertyChanged("MATHANHPHO");
					this.OnMATHANHPHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTHANHPHO", DbType="NVarChar(50)")]
		public string TENTHANHPHO
		{
			get
			{
				return this._TENTHANHPHO;
			}
			set
			{
				if ((this._TENTHANHPHO != value))
				{
					this.OnTENTHANHPHOChanging(value);
					this.SendPropertyChanging();
					this._TENTHANHPHO = value;
					this.SendPropertyChanged("TENTHANHPHO");
					this.OnTENTHANHPHOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHPHO_CHITIETTUYENDUNG", Storage="_CHITIETTUYENDUNGs", ThisKey="MATHANHPHO", OtherKey="MATHANHPHO")]
		public EntitySet<CHITIETTUYENDUNG> CHITIETTUYENDUNGs
		{
			get
			{
				return this._CHITIETTUYENDUNGs;
			}
			set
			{
				this._CHITIETTUYENDUNGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHPHO_THONGTINCANHAN", Storage="_THONGTINCANHANs", ThisKey="MATHANHPHO", OtherKey="MATHANHPHO")]
		public EntitySet<THONGTINCANHAN> THONGTINCANHANs
		{
			get
			{
				return this._THONGTINCANHANs;
			}
			set
			{
				this._THONGTINCANHANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHPHO_TTDOANHNGHIEP", Storage="_TTDOANHNGHIEPs", ThisKey="MATHANHPHO", OtherKey="MATHANHPHO")]
		public EntitySet<TTDOANHNGHIEP> TTDOANHNGHIEPs
		{
			get
			{
				return this._TTDOANHNGHIEPs;
			}
			set
			{
				this._TTDOANHNGHIEPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIETTUYENDUNGs(CHITIETTUYENDUNG entity)
		{
			this.SendPropertyChanging();
			entity.THANHPHO = this;
		}
		
		private void detach_CHITIETTUYENDUNGs(CHITIETTUYENDUNG entity)
		{
			this.SendPropertyChanging();
			entity.THANHPHO = null;
		}
		
		private void attach_THONGTINCANHANs(THONGTINCANHAN entity)
		{
			this.SendPropertyChanging();
			entity.THANHPHO = this;
		}
		
		private void detach_THONGTINCANHANs(THONGTINCANHAN entity)
		{
			this.SendPropertyChanging();
			entity.THANHPHO = null;
		}
		
		private void attach_TTDOANHNGHIEPs(TTDOANHNGHIEP entity)
		{
			this.SendPropertyChanging();
			entity.THANHPHO = this;
		}
		
		private void detach_TTDOANHNGHIEPs(TTDOANHNGHIEP entity)
		{
			this.SendPropertyChanging();
			entity.THANHPHO = null;
		}
	}
}
#pragma warning restore 1591
