CREATE DATABASE DB_Vieclam
USE DB_Vieclam
GO

CREATE TABLE TAIKHOAN_CN
(
	MATKCN INT IDENTITY(1,1) PRIMARY KEY,
	MASV CHAR(11) UNIQUE,	
	PASS NVARCHAR(30)
)
CREATE TABLE TAIKHOAN_DN
(
	MATKDN INT IDENTITY(1,1) PRIMARY KEY,
	EMAIL NVARCHAR(30) UNIQUE,
	PASS NVARCHAR(30),
)
CREATE TABLE NGANH
(
	MANGANH INT IDENTITY(1,1) PRIMARY KEY,
	TENNGANH NVARCHAR(50)
)
CREATE TABLE THANHPHO
(
	MATHANHPHO INT IDENTITY(1,1) PRIMARY KEY,
	TENTHANHPHO NVARCHAR(50),
)
CREATE TABLE NGOAINGU
(
	MANGOAINGU INT IDENTITY(1,1) PRIMARY KEY,
	TENNGOAINGU VARCHAR(30),
	TRINHDO NVARCHAR(10)
)
CREATE TABLE THONGTINCANHAN
(
	MATKCN INT PRIMARY KEY,
	HINHDD VARCHAR(100),
	HO NVARCHAR(50),
	TEN NVARCHAR(20),
	GIOITINH NVARCHAR(5) NOT NULL,
	NGAYSINH SMALLDATETIME NOT NULL, 
	EMAIL NVARCHAR(50) NOT NULL,
	SDT VARCHAR (12),
	DIACHI NVARCHAR(100),
	MATHANHPHO INT,
	FOREIGN KEY (MATKCN) REFERENCES TAIKHOAN_CN(MATKCN),
	FOREIGN KEY (MATHANHPHO) REFERENCES THANHPHO(MATHANHPHO),
)
CREATE TABLE HOSOXINVIEC
(
	MATKCN INT PRIMARY KEY, 
	MANGANH INT,
	HOCVAN NVARCHAR(100), 
	KINHNGHIEM NVARCHAR(MAX), 
	KYNANG NVARCHAR(MAX), 
	MANGOAINGU INT, 
	FOREIGN KEY (MATKCN) REFERENCES TAIKHOAN_CN(MATKCN),
	FOREIGN KEY (MANGANH) REFERENCES NGANH(MANGANH),
	FOREIGN KEY (MANGOAINGU) REFERENCES NGOAINGU(MANGOAINGU)
)
CREATE TABLE TTDOANHNGHIEP
(
	MATKDN INT PRIMARY KEY, 
	LOGO VARCHAR(100),
	TENDN NVARCHAR(100) NOT NULL, 
	QUYMODN INT,
	THONGTINDN NVARCHAR(MAX),
	DIACHI NVARCHAR(100), 
	MATHANHPHO INT,
	PHUCLOIDN NVARCHAR(100), 
	FOREIGN KEY (MATKDN) REFERENCES TAIKHOAN_DN(MATKDN),
	FOREIGN KEY (MATHANHPHO) REFERENCES THANHPHO(MATHANHPHO),
)
CREATE TABLE PHIEUDANGTUYEN
(
	MAPDT INT IDENTITY(1,1) PRIMARY KEY,
	MATKDN INT,
	NGAYDANGTIN SMALLDATETIME,
	THOIHANDANGTIN SMALLDATETIME,
	FOREIGN KEY (MATKDN) REFERENCES TAIKHOAN_DN(MATKDN)
)
CREATE TABLE CHITIETTUYENDUNG
(	
	MAPDT INT PRIMARY KEY,	
	TIEUDE NVARCHAR(50) NOT NULL,
	CHUCDANH NVARCHAR(100) NOT NULL,
	CAPBAC NVARCHAR(40) NOT NULL,
	MANGANH INT NOT NULL, 
	DIACHILAMVIEC NVARCHAR(100),
	MATHANHPHO INT,
	MUCLUONGTOITHIEU FLOAT,
	MUCLUONGTOIDA FLOAT,
	MOTACV NVARCHAR(50),
	YEUCAUCV NVARCHAR(100),
	KYNANG NVARCHAR(50) NOT NULL,
	NGUOILIENHE NVARCHAR(50) NOT NULL,
	EMAILLIENHE NVARCHAR(50) NOT NULL,
	TINHTRANG BIT,
	FOREIGN KEY (MANGANH) REFERENCES NGANH(MANGANH),
	FOREIGN KEY (MAPDT) REFERENCES PHIEUDANGTUYEN(MAPDT),
	FOREIGN KEY (MATHANHPHO) REFERENCES THANHPHO(MATHANHPHO),
)
CREATE TABLE NOPDON
(
	MATKCN INT NOT NULL,
	MAPDT INT NOT NULL,
	TINHTRANG BIT,
	FOREIGN KEY (MATKCN) REFERENCES TAIKHOAN_CN(MATKCN),
	FOREIGN KEY (MAPDT) REFERENCES PHIEUDANGTUYEN(MAPDT),
	PRIMARY KEY(MATKCN,MAPDT)
) 
CREATE TABLE LUOTUNGTUYEN
(
	MATKDN INT PRIMARY KEY,
	SOLUONG INT,
	FOREIGN KEY (MATKDN) REFERENCES TAIKHOAN_DN(MATKDN)
)
